[package]
name = "turboply"
version = "0.1.0"
edition = "2021"
description = "Accelerated drop-in replacement for pandas .apply()"

[lib]
name = "_turboply"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
rayon = "1.10"
numpy = "0.22"

[profile.release]
lto = true
codegen-units = 1
